"""Generates the runtime world-constant script from the canonical art config.

`art/config/world.toml` is the single source of truth for world scale.  The
runtime cannot read TOML cheaply at boot inside a packed export, so the values
are generated into a GDScript.  `check` regenerates in memory and diffs, so
drift between the two sides fails `rr.py check` loudly.
"""

from __future__ import annotations

import sys
from pathlib import Path

from . import config

TARGET_RELATIVE = Path("game") / "src" / "domain" / "world" / "world_constants.gd"

_TEMPLATE = """# GENERATED by `python tools/rr.py constants` from art/config/world.toml.
# Do not edit by hand: the file is overwritten and drift fails `rr.py check`.

class_name WorldConstants
extends RefCounted

# --- world scale ---
const TILE_SIZE := {tile_size}
const TILE_METRES := {metres_per_tile}
const HEIGHT_STEP := {height_step}
const CHUNK_SIZE := {default_chunk}
const MAP_WIDTH := {map_width}
const MAP_HEIGHT := {map_height}

# --- camera ---
const CAMERA_DEFAULT_YAW := {cam_yaw}
const CAMERA_FIXED_PITCH := {cam_pitch}
const CAMERA_ZOOM_CLOSE := {cam_close}
const CAMERA_ZOOM_DEFAULT := {cam_default}
const CAMERA_ZOOM_FAR := {cam_far}
const CAMERA_SNAP_DEGREES := {cam_snap}

# --- stations ---
const STATION_CATCHMENT := {station_catchment}
"""


def _fmt(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    raise ValueError(f"unsupported config value {value!r}")


def render(repo_root: Path) -> str:
    data = config.load(repo_root)
    world = data.get("world", {})
    camera = data.get("camera", {})
    station = data.get("station", {})
    missing = [
        key
        for key in (
            "tile_size",
            "height_step",
            "default_chunk",
            "map_width",
            "map_height",
            "metres_per_tile",
        )
        if key not in world
    ] + [
        key
        for key in (
            "default_yaw_degrees",
            "fixed_pitch_degrees",
            "zoom_close_tiles",
            "zoom_default_tiles",
            "zoom_far_tiles",
            "snap_degrees",
        )
        if key not in camera
    ] + [key for key in ("catchment_tiles",) if key not in station]
    if missing:
        raise ValueError(f"{config.config_path(repo_root)}: missing keys {missing}")
    return _TEMPLATE.format(
        tile_size=_fmt(float(world["tile_size"])),
        metres_per_tile=_fmt(float(world["metres_per_tile"])),
        height_step=_fmt(float(world["height_step"])),
        default_chunk=_fmt(int(world["default_chunk"])),
        map_width=_fmt(int(world["map_width"])),
        map_height=_fmt(int(world["map_height"])),
        cam_yaw=_fmt(float(camera["default_yaw_degrees"])),
        cam_pitch=_fmt(float(camera["fixed_pitch_degrees"])),
        cam_close=_fmt(float(camera["zoom_close_tiles"])),
        cam_default=_fmt(float(camera["zoom_default_tiles"])),
        cam_far=_fmt(float(camera["zoom_far_tiles"])),
        cam_snap=_fmt(float(camera["snap_degrees"])),
        station_catchment=_fmt(float(station["catchment_tiles"])),
    )


def generate(repo_root: Path) -> int:
    target = repo_root / TARGET_RELATIVE
    text = render(repo_root)
    target.parent.mkdir(parents=True, exist_ok=True)
    changed = not target.exists() or target.read_text() != text
    if changed:
        target.write_text(text)
        print(f"constants: wrote {target.relative_to(repo_root)}")
    else:
        print("constants: up to date")
    return 0


def check(repo_root: Path) -> int:
    target = repo_root / TARGET_RELATIVE
    expected = render(repo_root)
    if not target.exists():
        print(f"check: FAIL  {target} does not exist", file=sys.stderr)
        return 1
    actual = target.read_text()
    if actual != expected:
        print(
            "check: FAIL  world constants drifted from "
            f"{config.config_path(repo_root).relative_to(repo_root)}",
            file=sys.stderr,
        )
        print("           run: python tools/rr.py constants", file=sys.stderr)
        return 1
    return 0
