"""`rr.py art` — the headless art pipeline orchestrator.

Pure host Python (never imports bpy): generates throwaway Blender runner
scripts, supervises short-lived Blender subprocesses (thread pool over
subprocesses — processes are the isolation unit, threads only supervise),
enforces an input-hash build cache, publishes atomically from a staging
directory under a per-asset lock, and runs the named validation checks.

Commands (dispatched from tools/rr.py):
    art build <id> | --all [--jobs N] [--force] [--keep-temp]
    art validate <id> | --all
    art preview <id>
    art list
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from rr_common import art_assets, art_validation, toolchain  # noqa: E402

GENERATED_RELPATH = Path("game") / "generated"   # build output, git-ignored
MODELS_DIRNAME = "models"
MANIFESTS_DIRNAME = "manifests"
CACHE_FILENAME = ".cache.json"
LOGS_SUBDIR = Path("build") / "logs" / "art"
PREVIEWS_SUBDIR = Path("build") / "previews"
BLENDER_TIMEOUT_SECONDS = 600.0

RUNNER_TEMPLATE = '''"""Throwaway Open Rails art build runner (generated by rr.py art)."""
import json
import sys

ART_DIR = {art_dir!r}
JOB_FILE = {job_file!r}
sys.path.insert(0, ART_DIR)

def main():
    from railroad_art.context import BuildContext
    ctx = BuildContext.from_job_file(JOB_FILE)
    module = BuildContext.load_asset_module(ctx.job["asset_py"])
    module.build(ctx)
    summary = ctx.finalize()
    print("RR_ART_RESULT " + json.dumps(summary))

try:
    main()
except Exception:
    import traceback
    traceback.print_exc()
    sys.exit(3)
'''


class ArtCommandError(RuntimeError):
    pass


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


@dataclass
class BuildResult:
    asset_id: str
    status: str          # built | cached | failed
    detail: str = ""
    lod_triangles: dict | None = None


# --------------------------------------------------------------------------- versions


def library_version(repo_root: Path) -> str:
    """RAILROAD_ART_VERSION read from source text (host must not import bpy)."""
    path = repo_root / art_assets.LIBRARY_RELATIVE / "version.py"
    text = path.read_text(encoding="utf-8")
    match = re.search(r'RAILROAD_ART_VERSION\s*=\s*"([^"]+)"', text)
    if not match:
        raise ArtCommandError(f"cannot read RAILROAD_ART_VERSION from {path}")
    return match.group(1)


def blender_version_of(blender_exe: str) -> str:
    return toolchain.version_of(blender_exe)


def cached_blender_version(repo_root: Path, blender_exe: str) -> str:
    """Blender's version string, probed once and remembered so a fully-cached
    run spawns *no* Blender process at all (art-build spec scenario)."""
    cache = repo_root / GENERATED_RELPATH / CACHE_FILENAME
    if cache.is_file():
        try:
            data = json.loads(cache.read_text(encoding="utf-8"))
            if data.get("blender_executable") == blender_exe and data.get("blender_version"):
                return data["blender_version"]
        except (json.JSONDecodeError, OSError):
            pass
    version = blender_version_of(blender_exe)
    cache.parent.mkdir(parents=True, exist_ok=True)
    cache.write_text(json.dumps({"blender_executable": blender_exe,
                                 "blender_version": version}, indent=2) + "\n",
                     encoding="utf-8")
    return version


# --------------------------------------------------------------------------- job runner


@dataclass
class BlenderJob:
    repo_root: Path
    meta: art_assets.AssetMeta
    mode: str                       # build | preview
    out_dir: Path                   # staging: <temp>/out
    preview_dir: Path | None
    cache_key: str
    library_version: str
    blender_exe: str
    keep_temp: bool = False

    def run(self, log_dir: Path) -> BuildResult:
        temp_dir = Path(tempfile.mkdtemp(prefix=f"rr_art_{self.meta.id}_"))
        self.out_dir.mkdir(parents=True, exist_ok=True)
        log_path = log_dir / f"{self.meta.id}-{int(time.time() * 1000)}.log"
        log_dir.mkdir(parents=True, exist_ok=True)
        try:
            job_payload = {
                "repo_root": str(self.repo_root),
                "asset_py": str(self.meta.asset_py),
                "id": self.meta.id,
                "type": self.meta.type,
                "lod_class": self.meta.lod_class,
                "footprint": list(self.meta.footprint),
                "height": self.meta.height,
                "lod_levels": self.meta.lod_levels,
                "lod_auto": self.meta.lod_auto,
                "lod_ratios": list(self.meta.raw.get("lod", {}).get("ratios", [0.45, 0.15])),
                "required_states": self.meta.required_states,
                "company_regions": self.meta.company_regions,
                "mode": self.mode,
                "out_dir": str(self.out_dir),
                "preview_dir": str(self.preview_dir) if self.preview_dir else None,
                "cache_key": self.cache_key,
                "library_version": self.library_version,
                "blender_executable": self.blender_exe,
            }
            (temp_dir / "job.json").write_text(
                json.dumps(job_payload, indent=2), encoding="utf-8")
            runner = temp_dir / "runner.py"
            runner.write_text(RUNNER_TEMPLATE.format(
                art_dir=str(self.repo_root / "art"),
                job_file=str(temp_dir / "job.json")), encoding="utf-8")
            self.out_dir.mkdir(parents=True, exist_ok=True)

            with open(log_path, "wb") as log:
                log.write(f"# {' '.join([self.blender_exe])} job={job_payload['id']} "
                          f"mode={self.mode}\n# temp={temp_dir}\n".encode())
                log.flush()
                try:
                    proc = subprocess.run(
                        [self.blender_exe, "-b", "--factory-startup", "--python-exit-code", "3",
                         "-noaudio", "-P", str(runner)],
                        stdout=log, stderr=subprocess.STDOUT,
                        cwd=str(temp_dir), timeout=BLENDER_TIMEOUT_SECONDS, check=False)
                    code = proc.returncode
                except subprocess.TimeoutExpired:
                    return BuildResult(self.meta.id, "failed",
                                       f"Blender timed out after {BLENDER_TIMEOUT_SECONDS}s; "
                                       f"log: {log_path}")
            if code != 0:
                return BuildResult(self.meta.id, "failed",
                                   f"Blender exited {code}; log: {log_path}")
            if self.mode == "build":
                return self._finish_build(temp_dir)
            return BuildResult(self.meta.id, "built", str(self.preview_dir))
        finally:
            if not self.keep_temp:
                _rmtree(temp_dir)

    def _finish_build(self, temp_dir: Path) -> BuildResult:
        staged_glb = self.out_dir / MODELS_DIRNAME / f"{self.meta.id}.glb"
        staged_manifest = self.out_dir / MANIFESTS_DIRNAME / f"{self.meta.id}.json"
        if not staged_glb.is_file() or not staged_manifest.is_file():
            return BuildResult(self.meta.id, "failed",
                               "Blender reported success without producing model+manifest")
        # validate the staged copy before publication: a bad asset must not
        # reach game/generated/ (design.md "staged -> validated -> published")
        failures = art_validation.run_checks(self.repo_root, self.meta, self.out_dir)
        if failures:
            lines = "\n  ".join(str(f) for f in failures)
            return BuildResult(self.meta.id, "failed",
                               f"staged asset failed validation:\n  {lines}")
        manifest_text = staged_manifest.read_text(encoding="utf-8")
        published = publish(self.repo_root, self.meta.id, self.out_dir)
        if not self.keep_temp:
            _rmtree(self.out_dir)  # now-empty staging skeleton
        manifest = json.loads(manifest_text)
        return BuildResult(self.meta.id, "built", str(published["glb"]),
                           lod_triangles=manifest.get("lod_triangles"))


def _rmtree(path: Path) -> None:
    import shutil
    shutil.rmtree(path, ignore_errors=True)


# --------------------------------------------------------------------------- atomic publication


def publish(repo_root: Path, asset_id: str, staging: Path) -> dict[str, Path]:
    """Move staged outputs into game/generated under a per-asset lock.
    os.replace is atomic per file on the same volume."""
    generated = repo_root / GENERATED_RELPATH
    locks = generated / ".locks"
    locks.mkdir(parents=True, exist_ok=True)
    lock_path = locks / f"{asset_id}.lock"
    pairs = {
        "glb": (staging / MODELS_DIRNAME / f"{asset_id}.glb",
                generated / MODELS_DIRNAME / f"{asset_id}.glb"),
        "manifest": (staging / MANIFESTS_DIRNAME / f"{asset_id}.json",
                     generated / MANIFESTS_DIRNAME / f"{asset_id}.json"),
    }
    with open(lock_path, "w") as lock:
        _lock(lock)
        try:
            out = {}
            for kind, (src, dst) in pairs.items():
                dst.parent.mkdir(parents=True, exist_ok=True)
                os.replace(src, dst)
                out[kind] = dst
            return out
        finally:
            _unlock(lock)


def _lock(handle) -> None:
    try:
        import fcntl
        fcntl.flock(handle, fcntl.LOCK_EX)
    except ImportError:  # pragma: no cover - non-POSIX fallback: O_EXCL marker
        pass


def _unlock(handle) -> None:
    try:
        import fcntl
        fcntl.flock(handle, fcntl.LOCK_UN)
    except ImportError:  # pragma: no cover
        pass


# --------------------------------------------------------------------------- build


def build_asset(repo_root: Path, meta: art_assets.AssetMeta, *, blender_exe: str,
                blender_version: str, lib_version: str, library_hash: str,
                force: bool, keep_temp: bool) -> BuildResult:
    generated = repo_root / GENERATED_RELPATH
    cache_key = art_assets.asset_cache_key(repo_root, meta, library_hash,
                                           blender_version, lib_version)
    final_manifest_path = generated / MANIFESTS_DIRNAME / f"{meta.id}.json"
    final_glb = generated / MODELS_DIRNAME / f"{meta.id}.glb"
    if not force and final_glb.is_file() and final_manifest_path.is_file():
        try:
            existing = json.loads(final_manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            existing = {}
        if existing.get("cache_key") == cache_key:
            return BuildResult(meta.id, "cached", str(final_glb))

    # staging lives in the same volume as the final output (os.replace must not
    # cross devices) but in a private per-job directory
    staging = (repo_root / GENERATED_RELPATH / ".staging"
               / f"{meta.id}-{os.getpid()}-{int(time.time() * 1000)}")
    job = BlenderJob(repo_root=repo_root, meta=meta, mode="build",
                    out_dir=staging,
                    preview_dir=None, cache_key=cache_key,
                    library_version=lib_version, blender_exe=blender_exe,
                    keep_temp=keep_temp)
    return job.run(repo_root / LOGS_SUBDIR)


def cmd_build(args, repo_root: Path) -> int:
    metas = select_targets(repo_root, args)
    blender_exe = toolchain.find_blender(args.blender)
    blender_version = cached_blender_version(repo_root, blender_exe)
    lib_version = library_version(repo_root)
    library_hash = art_assets.hash_library(repo_root)

    jobs = max(1, int(args.jobs or 1))
    results: list[BuildResult] = []
    if jobs == 1 or len(metas) == 1:
        for meta in metas:
            results.append(build_one(repo_root, meta, args, blender_exe,
                                     blender_version, lib_version, library_hash))
    else:
        with ThreadPoolExecutor(max_workers=min(jobs, len(metas))) as pool:
            futures = [pool.submit(build_one, repo_root, meta, args, blender_exe,
                                   blender_version, lib_version, library_hash)
                       for meta in metas]
            results.extend(f.result() for f in futures)

    failed = 0
    for r in results:
        tag = {"built": "BUILT ", "cached": "cached", "failed": "FAILED"}[r.status]
        line = f"art build: [{tag}] {r.asset_id}"
        if r.lod_triangles:
            line += "  " + " ".join(f"{k}={v}" for k, v in sorted(r.lod_triangles.items()))
        print(line)
        if r.status == "failed":
            failed += 1
            print(f"    {r.detail}", file=sys.stderr)
    print(f"art build: {sum(r.status != 'failed' for r in results)}/{len(results)} ok")
    return 1 if failed else 0


def build_one(repo_root, meta, args, blender_exe, blender_version, lib_version,
              library_hash) -> BuildResult:
    # per-job staging lives inside the job temp dir's parent; keep_temp keeps it
    result = build_asset(repo_root, meta, blender_exe=blender_exe,
                         blender_version=blender_version, lib_version=lib_version,
                         library_hash=library_hash, force=args.force,
                         keep_temp=args.keep_temp)
    return result


# --------------------------------------------------------------------------- validate


def cmd_validate(args, repo_root: Path) -> int:
    metas = select_targets(repo_root, args)
    failed = 0
    for meta in metas:
        failures = art_validation.run_checks(repo_root, meta)
        if failures:
            failed += 1
            print(f"art validate: FAIL {meta.id}")
            for f in failures:
                print(f"  {f}")
        else:
            print(f"art validate: PASS {meta.id}")
    if failed:
        print(f"art validate: {failed} asset(s) failed", file=sys.stderr)
    return 1 if failed else 0


# --------------------------------------------------------------------------- preview


def cmd_preview(args, repo_root: Path) -> int:
    metas = select_targets(repo_root, args, allow_all=False)
    blender_exe = toolchain.find_blender(args.blender)
    failed = 0
    for meta in metas:
        preview_dir = repo_root / PREVIEWS_SUBDIR / meta.id
        job = BlenderJob(repo_root=repo_root, meta=meta, mode="preview",
                        out_dir=Path(tempfile.gettempdir()) / f"rr_preview_{meta.id}_{os.getpid()}",
                        preview_dir=preview_dir, cache_key="preview",
                        library_version=library_version(repo_root),
                        blender_exe=blender_exe, keep_temp=args.keep_temp)
        result = job.run(repo_root / LOGS_SUBDIR)
        if result.status == "built":
            count = len(list(preview_dir.glob("*.png")))
            print(f"art preview: {meta.id} -> {count} images in {preview_dir}")
            if count != 16:
                print(f"    expected 16 previews, found {count}", file=sys.stderr)
                failed += 1
        else:
            failed += 1
            print(f"art preview: FAILED {meta.id}: {result.detail}", file=sys.stderr)
    return 1 if failed else 0


# --------------------------------------------------------------------------- list


def cmd_list(args, repo_root: Path) -> int:
    metas = art_assets.discover_assets(repo_root)
    if not metas:
        print("art list: no assets found under art/assets/")
        return 0
    generated = repo_root / GENERATED_RELPATH
    width = max(len(m.id) for m in metas) + 2
    print(f"{'id'.ljust(width)}{'type'.ljust(12)}{'lod_class'.ljust(16)}"
          f"{'footprint'.ljust(14)}{'build'}")
    for meta in sorted(metas, key=lambda m: (m.category, m.id)):
        manifest = generated / MANIFESTS_DIRNAME / f"{meta.id}.json"
        glb = generated / MODELS_DIRNAME / f"{meta.id}.glb"
        if manifest.is_file() and glb.is_file():
            status = "built"
            try:
                status += " " + json.loads(manifest.read_text())["build_timestamp"]
            except Exception:
                pass
        else:
            status = "not built"
        print(f"{meta.id.ljust(width)}{meta.type.ljust(12)}{meta.lod_class.ljust(16)}"
              f"{str(list(meta.footprint)).ljust(14)}{status}")
    return 0


# --------------------------------------------------------------------------- targets


def select_targets(repo_root: Path, args, allow_all: bool = True) -> list[art_assets.AssetMeta]:
    metas = art_assets.discover_assets(repo_root)
    known = {m.id: m for m in metas}
    if getattr(args, "all", False):
        if not allow_all:
            raise ArtCommandError("--all is not supported for this command")
        if args.asset:
            raise ArtCommandError("pass either an asset id or --all, not both")
        if not metas:
            raise ArtCommandError("no assets found under art/assets/")
        return list(metas)
    if not args.asset:
        raise ArtCommandError("missing asset id (or use --all)")
    if args.asset not in known:
        raise ArtCommandError(f"unknown asset '{args.asset}'; known ids: "
                              f"{', '.join(sorted(known))}")
    return [known[args.asset]]


# --------------------------------------------------------------------------- entry


def main(args) -> int:
    repo_root = _repo_root()
    command = args.art_command
    try:
        if command == "build":
            return cmd_build(args, repo_root)
        if command == "validate":
            return cmd_validate(args, repo_root)
        if command == "preview":
            return cmd_preview(args, repo_root)
        if command == "list":
            return cmd_list(args, repo_root)
    except art_assets.AssetSourceError as exc:
        print(f"art {command}: source error: {exc}", file=sys.stderr)
        return 1
    except ArtCommandError as exc:
        print(f"art {command}: {exc}", file=sys.stderr)
        return 2
    print(f"art: unknown command {command}", file=sys.stderr)
    return 2
