# GENERATED by `python tools/rr.py constants` from art/config/world.toml.
# Do not edit by hand: the file is overwritten and drift fails `rr.py check`.

class_name WorldConstants
extends RefCounted

# --- world scale ---
const TILE_SIZE := 1.0
const TILE_METRES := 16.0
const HEIGHT_STEP := 0.25
const CHUNK_SIZE := 32
const MAP_WIDTH := 256
const MAP_HEIGHT := 256

# --- camera ---
const CAMERA_DEFAULT_YAW := 45.0
const CAMERA_FIXED_PITCH := 35.264
const CAMERA_ZOOM_CLOSE := 4.0
const CAMERA_ZOOM_DEFAULT := 28.0
const CAMERA_ZOOM_FAR := 96.0
const CAMERA_SNAP_DEGREES := 45.0

# --- stations ---
const STATION_CATCHMENT := 4.0
